# fly.toml app configuration file generated for btstream on 2024-07-26T10:05:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'btstream'
primary_region = 'ord'

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'

[mounts]
source = "db"
destination = "/db"
